/*********************************************************************************/
/************ THIS FILE IS GENERATED BY AWTK DESIGNER, DO NOT MODIFY *************/
/*********************************************************************************/
#include "awtk.h"

#ifdef AWTK_WEB
#include "assets.inc"
#else /*AWTK_WEB*/
#include "../res/assets.inc"
#endif /*AWTK_WEB*/

extern ret_t application_init(void);

extern ret_t application_exit(void);

#include "awtk_main.inc"
