import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR']

src_files = Glob('*.c')
src_files += Glob('custom_function/*.c')    
src_files += Glob('custom_widgets/*.c')
src_files += Glob('custom_widgets/*/*.c')

env.Program(os.path.join(BIN_DIR, 'demo'), src_files);