import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR']
CCFLAGS=env['CCFLAGS']

# 设置启用动画模式
CCFLAGS = CCFLAGS + " -DWATCH_ANIMATOR "

src_files = Glob('*.c')

src_files += Glob('custom_widgets/*.c')
src_files += Glob('window_controller/*.c')

src_files += Glob('custom_widgets/*/*.c')
src_files += Glob('window_controller/*/*.c')

env.Program(os.path.join(BIN_DIR, 'demo'), src_files, CCFLAGS = CCFLAGS);