import os
import sys
import platform

def getAwtkRoot():
    awtk_root = '../../awtk'
    return os.path.abspath(awtk_root)

sys.path.insert(0, getAwtkRoot())
import awtk_config as awtk

APP_CPPPATH = []
APP_CCFLAGS = ' -DLCD_W=800 -DLCD_H=480 '

APP_ROOT    = os.path.normpath(os.getcwd())
APP_BIN_DIR = os.path.join(APP_ROOT, 'bin')
APP_LIB_DIR = os.path.join(APP_ROOT, 'lib')

os.environ['APP_ROOT'] = APP_ROOT
os.environ['BIN_DIR'] = APP_BIN_DIR
os.environ['LIB_DIR'] = APP_LIB_DIR

APP_LIBS = []
APP_LIBPATH = [APP_LIB_DIR]

APP_TOOLS = None
if hasattr(awtk, 'TOOLS_NAME') and awtk.TOOLS_NAME != '' :
  APP_TOOLS = [awtk.TOOLS_NAME]

DefaultEnvironment(TOOLS     = APP_TOOLS,
  CPPPATH   = APP_CPPPATH + awtk.CPPPATH,
  LINKFLAGS = awtk.LINKFLAGS,
  LIBS      = APP_LIBS + awtk.LIBS,
  LIBPATH   = APP_LIBPATH + awtk.LIBPATH,
  CCFLAGS   = APP_CCFLAGS + awtk.CCFLAGS, 
  OS_SUBSYSTEM_CONSOLE=awtk.OS_SUBSYSTEM_CONSOLE,
  OS_SUBSYSTEM_WINDOWS=awtk.OS_SUBSYSTEM_WINDOWS)

SConscriptFiles=[
  'src/SConscript'
  ]
  
SConscript(SConscriptFiles)
