import os
import scripts.app_helper as app

ARGUMENTS['SHARED'] = 'False'
ARGUMENTS['IDL_DEF'] = 'False'
helper = app.Helper(ARGUMENTS)
helper.call(DefaultEnvironment)

SConscriptFiles = ['src/SConscript', 'tool/clock_pinter_gen/SConscript']
SConscript(SConscriptFiles)
